# Data Processing Notebook

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [7]:
# Load the dataset
file_path = '인구동태건수_및_동태율_추이_출생_사망_혼인_이혼__.xlsx'
data = pd.read_excel(file_path, sheet_name='데이터')

# Rename columns for clarity
data.rename(columns={data.columns[0]: 'Category'}, inplace=True)

data.head(10)

C:\Users\HyperPC\AppData\Roaming\Python\Python312\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Category,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,출생아수(명),435435.000,438420.000,406243.000,357771.000,326822.000,302676.000,272337.000,260562.000,249186.000,230028
1,사망자수(명),267692.000,275895.000,280827.000,285534.000,298820.000,295110.000,304948.000,317680.000,372939.000,352511
2,자연증가건수(명),167743.000,162525.000,125416.000,72237.000,28002.000,7566.000,-32611.000,-57118.000,-123753.000,-122483
3,조출생률(천명당),8.600,8.600,7.900,7.000,6.400,5.900,5.300,5.100,4.900,4.5
4,조사망률(천명당),5.300,5.400,5.500,5.600,5.800,5.700,5.900,6.200,7.300,6.9
5,자연증가율(천명당),3.300,3.200,2.500,1.400,0.500,0.100,-0.600,-1.100,-2.400,-2.4
6,합계출산율(명),1.205,1.239,1.172,1.052,0.977,0.918,0.837,0.808,0.778,-
7,출생성비(명),105.300,105.300,105.000,106.300,105.400,105.500,104.800,105.100,104.700,105.1
8,영아사망률(출생아 천명당),3.000,2.700,2.800,2.800,2.800,2.700,2.500,2.400,2.300,2.5
9,혼인건수(건),305507.000,302828.000,281635.000,264455.000,257622.000,239159.000,213502.000,192507.000,191690.000,193657

In [8]:
# Convert '2023' column to numeric and clean data
data['2023'] = pd.to_numeric(data['2023'], errors='coerce')
data.dropna(inplace=True)

# Save cleaned data
cleaned_file_path = 'population_trends_cleaned.csv'
data.to_csv(cleaned_file_path, index=False)
print(f"Cleaned data saved to {cleaned_file_path}")

Cleaned data saved to population_trends_cleaned.csv

In [10]:
data.head(7)

,Category,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,출생아수(명),435435.0,438420.0,406243.0,357771.0,326822.0,302676.0,272337.0,260562.0,249186.0,230028.0
1,사망자수(명),267692.0,275895.0,280827.0,285534.0,298820.0,295110.0,304948.0,317680.0,372939.0,352511.0
2,자연증가건수(명),167743.0,162525.0,125416.0,72237.0,28002.0,7566.0,-32611.0,-57118.0,-123753.0,-122483.0
3,조출생률(천명당),8.6,8.6,7.9,7.0,6.4,5.9,5.3,5.1,4.9,4.5
4,조사망률(천명당),5.3,5.4,5.5,5.6,5.8,5.7,5.9,6.2,7.3,6.9
5,자연증가율(천명당),3.3,3.2,2.5,1.4,0.5,0.1,-0.6,-1.1,-2.4,-2.4
7,출생성비(명),105.3,105.3,105.0,106.3,105.4,105.5,104.8,105.1,104.7,105.1

In [9]:

# Convert '2023' column to numeric
data['2023'] = pd.to_numeric(data['2023'], errors='coerce')

# Check for missing values
missing_values = data.isnull().sum()

# Drop rows with missing values (if applicable)
data.dropna(inplace=True)

# Display summary of missing values before and after cleaning
print("Missing values after cleaning:")
print(data.isnull().sum())

# Save cleaned data to a new CSV
cleaned_file_path = 'population_trends_cleaned.csv'
data.to_csv(cleaned_file_path, index=False)
print(f"Cleaned data saved to {cleaned_file_path}")

Missing values after cleaning:
Category    0
2014        0
2015        0
2016        0
2017        0
2018        0
2019        0
2020        0
2021        0
2022        0
2023        0
dtype: int64
Cleaned data saved to population_trends_cleaned.csv